CORRECT_TIME: 1.0
ENTITIES:
- AcademicDegree
- AcademicLoad
- Auditor
- DirectionOfPreparation
- Discipline
- Enclosures
- Group
- HEI
- Institute
- StudyWeek
- Teacher
- Title
- TrainingProfiles
- TypesOfOccupations
- University
INACTIVE_DAYS: 2
ORG: Students-of-the-city-of-Kostroma
REPO: Student-timetable
TEAM: Elite
TO_STRING:
  CreateEvent:
  - payload.ref
  DeleteEvent:
  - payload.ref
  IssueCommentEvent:
  - payload.issue.number
  - payload.comment.body
  IssuesEvent:
  - payload.action
  - payload.issue.number
  - payload.issue.title
  PullRequestEvent:
  - payload.action
  - payload.pull_request.number
  - payload.pull_request.title
  PullRequestReviewCommentEvent:
  - payload.pull_request.number
  - payload.comment.body
  PullRequestReviewEvent:
  - payload.review.state
  - payload.pull_request.number
  - payload.pull_request.title
  PushEvent:
  - payload.ref
  - payload.commits.0.message
  added_to_project:
  - issue.number
  - issue.title
  assigned:
  - assignee.login
  - issue.number
  - issue.title
  base_ref_changed:
  - issue.number
  - issue.title
  closed:
  - issue.number
  - issue.title
  comment_deleted:
  - issue.number
  - issue.title
  connected:
  - issue.number
  - issue.title
  head_ref_deleted:
  - issue.number
  - issue.title
  labeled:
  - label.name
  - issue.number
  - issue.title
  mentioned:
  - issue.number
  - issue.title
  merged:
  - issue.number
  - issue.title
  milestoned:
  - milestone.title
  - issue.number
  - issue.title
  moved_columns_in_project:
  - issue.number
  - issue.title
  ready_for_review:
  - issue.number
  - issue.title
  referenced:
  - issue.number
  - issue.title
  renamed:
  - issue.number
  - rename.from
  - rename.to
  reopened:
  - issue.number
  - issue.title
  review_dismissed:
  - issue.number
  - issue.title
  review_request_removed:
  - issue.number
  - issue.title
  review_requested:
  - issue.number
  - requested_reviewer.login
  - requested_team.name
  - issue.title
  subscribed:
  - issue.number
  - issue.title
  unassigned:
  - assignee.login
  - issue.number
  - issue.title
  unlabeled:
  - label.name
  - issue.number
  - issue.title
  unsubscribed:
  - issue.number
  - issue.title
